local progress = require("lazynator.progress")
local config = require("lazynator.config")

local function reset()
  progress.reload()
  vim.fn.delete(progress.path())
  progress.reload()
  config.setup({})
end

describe("progress", function()
  before_each(reset)

  it("is saved in stdpath('data')/lazynator/progress.json", function()
    eq(vim.fn.stdpath("data") .. "/lazynator/progress.json", progress.path())
  end)

  it("goes new -> learning -> learned after N presses in a row", function()
    config.setup({ learned_after = 3 })
    eq("new", progress.state("<leader>bd"))
    progress.press("<leader>bd")
    eq("learning", progress.state("<leader>bd"))
    progress.press("<leader>bd")
    eq("learning", progress.state("<leader>bd"))
    progress.press("<leader>bd")
    eq("learned", progress.state("<leader>bd"))
  end)

  it("moves a learned key back to learning on a nudge, and counts again from 0", function()
    config.setup({ learned_after = 2 })
    progress.press("<leader>e")
    progress.press("<leader>e")
    eq("learned", progress.state("<leader>e"))
    progress.nudge("<leader>e")
    eq("learning", progress.state("<leader>e"))
    eq(0, progress.get("<leader>e").streak)
    progress.press("<leader>e")
    eq("learning", progress.state("<leader>e"))
    progress.press("<leader>e")
    eq("learned", progress.state("<leader>e"))
  end)

  it("a nudge alone makes a new key learning", function()
    progress.nudge("<leader>gg")
    eq("learning", progress.state("<leader>gg"))
  end)

  it("survives a restart (file is read again)", function()
    progress.press("<leader>ff")
    progress.press("<leader>ff")
    progress.nudge("<leader>bd")
    progress.save()
    progress.reload()
    eq(2, progress.get("<leader>ff").presses)
    eq(1, progress.get("<leader>bd").nudges)
    local data = vim.json.decode(table.concat(vim.fn.readfile(progress.path()), "\n"))
    eq(2, data.keys["<leader>ff"].presses)
  end)

  it("does not lose presses saved by another Neovim at the same time", function()
    progress.press("<leader>ff")
    progress.save()
    -- another Neovim writes its own press to the file
    local data = vim.json.decode(table.concat(vim.fn.readfile(progress.path()), "\n"))
    data.keys["<leader>ff"].presses = data.keys["<leader>ff"].presses + 1
    data.keys["<leader>ff"].streak = data.keys["<leader>ff"].streak + 1
    data.keys["L"] = { presses = 4, streak = 4, nudges = 0 }
    vim.fn.writefile({ vim.json.encode(data) }, progress.path())
    progress.press("<leader>ff")
    progress.save()
    progress.reload()
    eq(3, progress.get("<leader>ff").presses)
    eq(4, progress.get("L").presses)
  end)

  it("starts fresh when the file is broken", function()
    vim.fn.mkdir(vim.fn.fnamemodify(progress.path(), ":h"), "p")
    vim.fn.writefile({ "{not json" }, progress.path())
    progress.reload()
    eq("new", progress.state("<leader>bd"))
    progress.press("<leader>bd")
    progress.save()
    progress.reload()
    eq(1, progress.get("<leader>bd").presses)
  end)
end)
